### ISSUE TITLE
What is the default execution timeout

### ISSUE THREAD

**Issue by ljpassingby** [zeroturnaround/zt-exec#103]
hey, there is my question.
For the code `new ProcessExecutor().command(anyCommand).timeout(60, TimeUnit.SECONDS).execute();`  as an example.
If we use such `timeout(60, TimeUnit.SECONDS)` funciton, we could set the execution timeout. So, if we do not use the `timeout()` function, what is the default execution timeout? Will it wait until the `command` finish?

**Comment by nemecec** [comment]
> So, if we do not use the timeout() function, what is the default execution timeout? Will it wait until the command finish?

Yes, it will wait for the process to finish. You can check the JavaDoc of `execute()` method:

https://github.com/zeroturnaround/zt-exec/blob/933f571414836889e7162152293c595b49baa8ae/src/main/java/org/zeroturnaround/exec/ProcessExecutor.java#L895
