### ISSUE TITLE
Support Java Modules

### ISSUE THREAD

**Issue by aalmiray** [zeroturnaround/zt-exec#105]
I'd be great if the library supplied a full Java module descriptor. It's possible to keep bytecode baseline compatible with Java  8 while providing a full module descriptor thanks to [ModiTect](https://github.com/moditect/moditect). If interested I can send a PR to make it happen.

**Comment by aalmiray** [comment]
Do you have an estimate on when the next release could be posted? Thanks 😅

**Comment by nemecec** [comment]
> Do you have an estimate on when the next release could be posted? Thanks 😅

I wanted to check if this change actually works in CI, with Java 6. Then I noticed that the CI integration does not work anymore. So I was thinking about porting the CI over from CircleCI to GitHub actions. And then busy times at day-job took over. So it's a bit of a rabbit-hole.
And next 2 weeks are quite hectic so I'm not sure if I will find the time to work on this.
How urgent is it for you?

**Comment by aalmiray** [comment]
@nemecec Understood. I don't have a high urgency at the moment. Just making sure all dependencies consumed by JReleaser are modular at some point. 

I could send a PR for building with GitHub Actions if it helps 😅

**Comment by nemecec** [comment]
Help with GitHub actions would be much appreciated, thanks! Ideally it would build the code with Java 9 and then run the tests with Java 6, Java 7, Java 8, Java 9, Java 11 (LTS) and Java 17 (LTS).

**Comment by nemecec** [comment]
@MastaP, this would be useful indeed. Want to follow up on that with an issue and a PR? ;-)

**Comment by nemecec** [comment]
I now added a GitHub action to build and test the code with Java 6, 8, 11 and 17. I also added a section to `README.md` with note about dependencies. I did not add Animal Sniffer Maven Plugin -- instead, I configured the java compiler to use the release option ([what is -release option?](https://www.baeldung.com/java-compiler-release-option)).
