### ISSUE TITLE
Enable to read error stream into a buffer

### ISSUE THREAD

**Issue by reinra** [zeroturnaround/zt-exec#13]

**Comment by drothmaler** [comment]
Hi, I'm intereset in this feature and I'd like to Implement it and to submit a PR... 
Domyou have an implementation hints?
I thought about simply adding a `errorOutput` Property (of type `ProcessOutput`) to the `ProcessResult`... Is this OK, or did you think of anything else?

**Comment by reinra** [comment]
Hi,
sry that I've added this issue here. The reason why I haven't implemented it is that I haven't had a use case for it. By default the output and error and merge together so the buffered output contains both. Do you actually need this feature or did you just want to try to add some new cool feature?

**Comment by drothmaler** [comment]
Yes unfortunately I have to deal with some programs, that don't have well defined exit value. 
So I'd like to use the error stream as an indicator, if the process returned any errors.

**Comment by reinra** [comment]
Ok, you can implement it by
1. adding new field (of type ProcessOutput) to ProcessResult. I would call it 'error' for simplicity.
2. Improve WaitForProcess (add a nullable field ByteArrayOutputStream err).
3. Add readError field and readError(boolean) method to ProcessExecutor.
4. Update ProcessExecutor.startInternal to make use of this readError field.

Basically just follow how the readOutput mechanism works everywhere.
