### ISSUE TITLE
How to create a session

### ISSUE THREAD

**Issue by rahmanusta** [zeroturnaround/zt-exec#21]
Hi, Is there way to use zt-exec in session based. Can I bind it to System.in and System.out continiously?

**Comment by toomasr** [comment]
Can you explain the session based approach a bit more?

**Comment by rahmanusta** [comment]
For example;

new ProcessExecutor().in(System.in).out(System.out).err(System.err).join();

After that, when you type commands to console, you will see out or error in session manner.

**Comment by reinra** [comment]
Hi,
ProcessExecutor expects a specific command to be executed, it can't be read from an input stream directly (you can implement it yourself either in Java or in some other language). If you know the command you can use the System streams like this:
```java
new ProcessExecutor("command").redirectInput(System.in).redirectOutput(System.out).redirectError(System.err).execute();
```

**Comment by rahmanusta** [comment]
Thanks
