### ISSUE TITLE
Force destruction of a known PID

### ISSUE THREAD

**Issue by footloosejava** [zeroturnaround/zt-exec#22]
For Windows... We have some processes that __ just __ won't __ die -- in particular, there are 16-bit processes that are run in the ntvdm.exe subsystem and even thought the Process.destroyForcibly() reports that they are dead, they are still alive because Java only kills the consolehost or cmd.exe not the spawned thread in ntdvm.exe.

Also, getting the exit value fails (or throws) because the process is still alive even after Process claims it died.

So ... I have my own library for Process that scans the process output for a self reporting PID.

If the process exit is overdue, then I call my taskkiller ... and it goes through all the PID's found and kills them all via the windows taskkill command.

Hence, all my processes are started via a 'cmd /c' batchfile that calls getpid.exe and then reports the errorlevel as the PID like this:

%BATCHOME%\manage\getpid.exe
echo GETPID.EXE: THE CURRENT PID IS %errorlevel%
:: then call program that does what we need done.
:: by running "taskkill.exe /f /t  /pid {pid}" we can kill the PID and any children in the tree

The getpid.exe program is created by running the batchfile code pasted at the bottom of this post.

I'll throw this out there and then maybe you can integrate a way to collect PID's using some program specified magic cookie and then be able to verifiably destory them similar to this.

The PID's are collected by my process reader. Here is the code to my process destroyer util.

    public static List<Throwable> kill(String pid, Process p) throws InterruptedException {
        List<Throwable> exceptions = new ArrayList();
                try {
                    callWindowsTaskkill(p, pid, exceptions);
                } catch (final KillException ke) {
                    exceptions.add(ke);
                }
        return exceptions;
    }

    private static void destroyWait(Process p) throws InterruptedException, KillException {
        p.destroyForcibly();
        logger.debug("destroyForcibly called. Will wait 100 ms for official termination.");
        if (p.waitFor(100, TimeUnit.MILLISECONDS)) {
            logger.info(">> exit code: {}", p.exitValue());
        } else {
            throw new KillException("Process will not die after calling destroyForcefully() and waiting 100ms.", p);
        }
    }

    private static void callWindowsTaskkill(Process p, String pid, List<Throwable> exceptions) throws InterruptedException, KillException {
        logger.info("calling kill on pid: {}", pid);
        BatchSession<LineGobbler> bs = getKillTask(pid).call();
        for (Throwable t : bs.getExceptions()) {
            exceptions.add(t);
        }
        if (bs.getGobbler().isPresent()) {
            boolean dead = false;
            for (String line : bs.getGobbler().get().getLines()) {
                logger.debug(line);
                if (StringUtils.startsWithIgnoreCase(line, "SUCCESS: The process with PID " + pid + " ")
                        && StringUtils.endsWithIgnoreCase(line, " has been terminated.")) {
                    dead = true;
                } else if (StringUtils.containsIgnoreCase(line, "ERROR: The process \"" + pid + "\" not found")) {
                    dead = true;
                }
            }
            if (!dead) {
                throw new KillException("Process with pid " + pid + " will not die after being destroyed by 'taskkill'", p);
            }
        }
    }

    private static BatchTask<LineGobbler> getKillTask(String pid) {
        String id = pid + "-killer";
        return BatchTask.builder()
                .setTimeout(Duration.ofSeconds(10))
                .setTimeoutAction(BatchTask.TimeoutAction.taskkill)
                .build(id, new ProcessBuilder("taskkill.exe", "/f", "/t", "/pid", pid),
                        () -> new LineGobbler(id, StandardCharsets.ISO_8859_1));
    }

========================================================================

@Echo Off
Rem Script made using BHX { consolesoft.com/p/bhx }
SetLocal EnableExtensions EnableDelayedExpansion
Set "bin=getpid.ex_"
Set "size=643"
For %%# In (
"getpid.exe"
"!bin!" "!bin!.da" "!bin!.tmp"
) Do If Exist "%%#" (Del /A /F /Q "%%#" >Nul
If ErrorLevel 1 Exit /B 1 )
Findstr /B /N ":+res:!bin!:" "%~f0" >"!bin!.tmp"
(Set /P "inioff=" &Set /P "endoff=") <"!bin!.tmp"
For /F "delims=:" %%# In ("!inioff!") Do Set "inioff=%%#"
For /F "delims=:" %%# In ("!endoff!") Do Set "endoff=%%#"
Set ".=set o=createobject(#scripting.filesystemobject#)"
Set ".=!.!: set w=createobject(#adodb.stream#)"
Set ".=!.!: set r=o.opentextfile(#%~f0#,1,0,0)"
Set ".=!.!: w.charset=#windows-1252# : w.type=2 : w.open"
Set ".=!.!: for i=1 to !inioff! step 1 : r.readline : next"
Set ".=!.!: do while i<!endoff! : d=r.readline"
Set ".=!.!: for j=1 to len(d) step 2"
Set ".=!.!: w.writetext chr(cbyte(#&h#&mid(d,j,2)))"
Set ".=!.!: next : i=i+1 : loop"
Set ".=!.!: w.savetofile #!bin!#,2"
Set ".=!.!: w.close : r.close"
Set ".=!.!: set w=nothing : set r=nothing : set o=nothing"
Set ".=!.:#="!"
Echo !.!>"!bin!.da"
Set "ret=1"
Cscript.exe /B /E:vbs "!bin!.da" >Nul
For %%# In ("!bin!") Do If "%%~z#"=="!size!" Set "ret=0"
If "0"=="!ret!" Expand.exe -r "!bin!" -F:* . >Nul
If ErrorLevel 1 Set "ret=1"
Del /A /F "!bin!" "!bin!.da" "!bin!.tmp" >Nul
Exit /B !ret!

:+res:getpid.ex_:
4D5343460000000083020000000000002C000000000000000301010001000000
000000004700000001000100000800000000000000009645357D200067657470
69642E65786500DD597C9934020008434BF38D9AC0C0CCC0C0C002C4FFFF3330
EC6080000706C2A00188F9E477F1316CE13CABB883D1E7AC62484666B1424151
7E7A5162AE4272625E5E7E894252AA4251699E42669E828B7FB0426E7E4AAA1E
2F2F970AD48C005706061F466686A7A9334260E63E60E067E66664126760823A
0C0836080009010684EB406C268834234219C4E140F1E21606B0BF181814A0FA
04E0FA05903D61C0C0F08708BF920A5C80E6CAE091D72B49AD2801B9859101EE
173046020A0C01097A45298925890C0C2250AF208709C2CB060E7A9910757FA0
7E02AB63C3507700DD1DA19D4FC3C3821BDFF800D51F7751019B7C9C4505A4FB
C50620D179B8F90D87E181E6DFFF4B225E2C070AF46EDDF3F7FFFFCE1215964E
1995E3AD208E0E5075E7F1171381B240C5AD074A455F5B4015BC68810996A85A
EE3D02545CFA14245C0A14EE6EBD02E437BF61E94DFD121D171F7BB8B7448D01
24190194045A892AD1BB471DEADEE637122F5CFF03DDC0A2F2C21428340119FC
57F530706000D101503A044A4740691728ED03A1FF83523D28ED43E89106DC9D
9DAD14344A5272758D34154CF42CF40C4762288C5CA0618060BF3180945BD840
02503C0F88BB80780610AF03E2030684E582189C73F28B533D12F352725219F6
303817A52696A486E4E7E764A4E614181B05E725161467E4038B427146D78ACC
9280A2FCE4D4E26286FD8CEEA925CEA54545A9793031CF14864E6628DBD8C82D
B3A8B8249CA11B21E2072C51C361653A36ECED1AE4E7EA636CA4979293331AF3
100000
:+res:getpid.ex_:

**Comment by reinra** [comment]
Thank you very much for this feedback.
In zt-exec I have knowingly kept closing processes simple by just relying on the Java implementation. Doing it properly is more complex and I have a separate project for this which just isn't open source yet.  
In your case I would simplify the approach by getting the PID of the forked process in Java directly instead of using a wrapper process. See http://www.golesny.de/p/code/javagetpid
You should be able to integrate your approach with zt-exec by calling ProcessExecutor.stopper(ProcessStopper). It allows you to override how the process is closed.

**Comment by footloosejava** [comment]
Thanks, I'll look at that. I'll take any good way of using Java to get the PID :)

**Comment by footloosejava** [comment]
That's great!!! I am so glad I chimed in with my verbose solutions.
because  http://www.golesny.de/p/code/javagetpid rocks.

Just tried and that solves a few problems!!

Thank you again!

**Comment by reinra** [comment]
That's great :)
I'll also hope to open-source the process stopping project during this week.

**Comment by footloosejava** [comment]
The jna solution really works well. I have greatly simplified my code with this. I look forward to seeing your open source project.
