### ISSUE TITLE
Closing a Process InputStream hangs on some processes

### ISSUE THREAD

**Issue by footloosejava** [zeroturnaround/zt-exec#23]
(1) I noticed that you have this is StandardProcessCloser and what I find is that getInputStream() can hang when Process.destroy() has already been called:

try {
      process.getInputStream().close();
}catch (IOException e) {
     log.error("Failed to close process input stream:", e);
     caught = e;
}

(2) Also, I find that InputStream.close() can hang, unless process.destroy() is called first.

So, the key for me is to make sure I obtain the inputStream before calling close() and then also make sure to call destroy before forcibly closing the streams:

For example, here is a process that I think requires that correct sequence or it will not destroyForcibly on Windows:

@ECHO OFF
ECHO WELCOME TO HUNG
:loop
for /l %%n in (1,1,10000000000) do set temp=
goto:loop
ECHO UNREACHABLE
EXIT

Furthermore, if the Process is started as a 16-bit DOS executable, then even though Process reports that it is dead, it is still alive and well in the ntvdm.exe subsystem for running windows-on-windows 16-bit exe's in the system32 environment.

Which is to say, that although the batch file above needs a specific order to shutdown, if it spawns a 16-but program then that program must be forcibly killed by taskkill.

**Comment by footloosejava** [comment]
This is my workflow:

 try {
            Process p = processBuilder.start();
            InputStream pis = p.getInputStream();

            // when we set this, it stops waiting and starts reading
            gobbler.setInputStream(pis);

            OutputStream pos = p.getOutputStream();
            InputStream perr = p.getErrorStream();

            Duration elapsed = Timer.time(() -> {
                gobblerThread.join(timeout.toMillis());
            });

            if (gobblerThread.isAlive() || p.isAlive()) {
                logger.debug("Elapsed time: {}", elapsed);
                throw new GobblerTimeoutException(p, pis, pos, perr, "Still alive after timeout of: " + timeout);
            }

            session.setExitCode(p.exitValue());

            // this is only thrown in the getProcess.start() method
        } catch (final IOException ex) {
            session.addException(ex);
            // we throw this on the timeout

        } catch (GobblerTimeoutException gte) {
            session.addException(gte);
            // first we close all streams
            Process p = gte.getProcess();
            p.destroy();
            
            OutputStream pos = gte.getOutputStream();
            try {
                if (pos != null) {
                    pos.flush();
                    logger.debug("Flushed process outputStream: {}", p);
                }
            } catch (Exception e) {
                logger.debug("Error flushing process outputStream: " + e);
            }

            streamCloser(pos, p);
            streamCloser(gte.getInputStream(), p);
            streamCloser(gte.getErrorStream(), p);
            
            p.waitFor(100, TimeUnit.MILLISECONDS);
            if (gobblerThread.isAlive() || p.isAlive()) {
                switch (timeoutAction) {
                    default:
                    case kill:
                        List<Throwable> exs = BatchTaskUtils.kill(gobbler.getPIDs(), gte.getProcess());
                        exs.forEach(it -> session.addException(it));
                        break;
                    case abandon:
                        logger.info("Abandoning process as instructed: {}", timeoutAction);
                }
            } else {
                logger.info("Process died after streams closed: {}", p);
            }
        } finally {
            // if gobbler thread did not die within timeout, we proceed to kill getProcess
            // then we interrupt. This might get us more inout being read during the kill getProcess
            gobblerThread.interrupt();
            gobblerThread.join();
            gobbler.getException().ifPresent(it -> {
                session.addException(it);
            });

            Duration time = Duration.ofMillis(stopWatch.getTime());
            session.setProcessTime(time);
        }

        return session;
    }

    protected void streamCloser(Closeable closeable, Process p) throws InterruptedException {
        try {
            if (closeable != null) {
                closeable.close();
                logger.debug("Closed {} from : {}", closeable, p);
            }
        } catch (Exception e) {
            logger.debug("Error closing {} from {}: ", closeable, p);
        }
    }

**Comment by reinra** [comment]
zt-exec doesn't handle close process trees - it's only tries to close the immediate forked process.
I have tried stopping the process before its streams. This causes another issues that you can't read the full output of the process e.g. if it has shutdown handlers or it just did something between closing the streams and getting terminated. I'll try to open-source another project sooner which is only for stopping the processes. Then we could discuss how it works for your case.

**Comment by footloosejava** [comment]
I guess I want to throw out three scenarious then:

(1) the process can be killed by Java via destroy() and/or destroyForcibly().

(2) the process can be killed in (1) and then verify that the PID is killed.

(3) special case where the process must be killed using 'taskkill.exe /f /t /pid {pid}.

Case #3 exists where the process tree must be killed, and where if the process PID is killed in (1) or (2) then the Windows system cannot initiate killing the tree.

For example, my dreaded 16-bit NTVDM.exe subprocess. If the Java uses destroy() or destroyForcibly(), the immediate forked process is killed, but ... when taskkill is called it cannot use the PID anyomore because it does not exist.

So, I have tried (1) and (2) but with some processes, the PID must be taskkilled first so that Windows can kill the tree from a live/running/stalled PID.

So, it would be nice to have those three strategies for ending an overdue process.

**Comment by footloosejava** [comment]
One more.
Re: zt-exec doesn't handle close process trees - it's only tries to close the immediate forked process.

If the process is 16-bit, then it is impossible to kill the immediate forked process, because it is co-opted by ntvdm and run in the subsystem. And I understand this is a corner-case, but there are 100 programmers tonight around the world losing sleep because they have some windows legacy system process written in the 1970's and 1980's that just won't die any of the the normal ways ...

**Comment by reinra** [comment]
Here's a new project called zt-process which should handle stopping processes better.
https://github.com/zeroturnaround/zt-process
Let me know whether it's helpful for you.
