### ISSUE TITLE
Mid-execution processing of streams

### ISSUE THREAD

**Issue by marcreichman-pfi** [zeroturnaround/zt-exec#26]
I can't seem to find a straightforward way to create or pass in some threads to consume stderr/stdout streams while a process is executing. Simple use cases for this are updating progress information based on console output of the process, etc.

If this is something reasonably easy to do (e.g. implement an interface, pass in a Runnable/Callable, etc.) then documentation for that would be helpful.

Thanks!

**Comment by reinra** [comment]
Thanks for the question. Please use
```java
processExecutor.redirectOutput(mew LogOutputStream() {
  protected void processLine(String line) {
    // handle line
  }
});
```
By default it handles both stdout and stderr. If you call redirectError() or redirectErrorStream(false) they are separated.
I'll also update the documentation.
