### ISSUE TITLE
Is there a way to set the process priority

### ISSUE THREAD

**Issue by PH0lder** [zeroturnaround/zt-exec#29]
I really like the simplicity of your code, I have a test app written that works quite well with it.  The one thing that I am unable to do, is to set the priority of the executed process.  In the past, I used the Java ProcessBuilder and had platform specific code to use nice on Unix/Linux/Mac and use START /LOW on Windows.

I could still use START/LOW on Windows, but the problem I was trying to solve that brought me to trying this library, was that of the process tree getting disconnected.  I want to have it be the case that closing the Java VM (CTRL-C into a CMD window which is launched from the command line using java -jar) will also cause the background tasks to shutdown.  My current approach is unable to manage this, but I was hoping using this library could allow it... but I *have* to have the processes running at the lowest possible priority, as they are long running tasks attempting to consume only idle cycles and I need my machine to otherwise stay responsive.

**Comment by reinra** [comment]
Try ProcessExecutor.destroyOnExit(). This should stop the launched process when you press Ctrl+C. However if the JVM may get killed forcefully it does not run the shutdown hooks and your launched process remains running. To overcome you could make your launched process ping the parent process and shutdown itself if unable to reach the parent. If you can't change the launched process you could create a separate small watchdog app that does it for you.

ProcessExecutor just wraps the ProcessBuilder so it has no support for process priorities. You can try the START /LOW and see how it works together with destroyOnExit(). It depends whether that START command stops its child process as well. In case it just spawns the target process and stops itself immediately it can't stop the target process later obviously.

**Comment by PH0lder** [comment]
If I use CMD.EXE /C START /LOW then START seems to disconnect everything, and I would end up having to basically write my own version of START... which doesn't sound like my kind of fun.  So, instead I focused on using JNA to find a way to set the process priority.  This allows me to use destroyOnExit() as you suggested.

After lots of Googling and a bit of struggle, I got something to work, which I would be happy to share here, if you're interested in maybe adding a platform specific extra call such as  setWin32ProcessPriority(W32_PROCESS_PRIORITY_IDLE).

The issue I have, right now, is that I need access to the Process, but I also want to use Future<> so I have to call an deprecated function.  Here's a sample of what I have:

    final StartedProcess sp = new ProcessExecutor().command(command).
      redirectOutput(new NullOutputStream()).
      exitValue(0).directory(new File("R:\\Temp\\")).     
      redirectError(new NullOutputStream()).
      destroyOnExit().readOutput(true).
      start();

    final Process p = sp.getProcess();
    SetProcessPriority.setProcessPriority(p, ProcessPriorityClass.IDLE_PRIORITY_CLASS);
    final Future<ProcessResult> f = sp.getFuture();
    return f;

Maybe you can supply a way to put in my own handler that gets passed the Process so I can use it to set the priority?

**Comment by reinra** [comment]
Try to implement ProcessListener.afterStart(Process, ProcessExecutor).
You can register the ProcessListener by calling ProcessExecutor.addListener()
If your solution works we could also include it in the zt-exec.
