### ISSUE TITLE
Waiting for stdout, stderr pumping threads forever 

### ISSUE THREAD

**Issue by szhem** [zeroturnaround/zt-exec#31]
Hello,

I've tried to spawn `sh -c 'sleep 60'` and then to kill this child process with `kill -9` from the shell.
Although `WaitForProcess` successfully determines that child process died, `PumpStreamHandler` is waiting for stdout, stderr pumping threads to finish, that may never happen due to the following issue: [Process.getInputStream().read() method hangs for destroyed Process](https://bugs.openjdk.java.net/browse/JDK-4311711).

Is it possible to add an option to this lib, that will make `PumpStreamHandler` to wait for the threads to die in the timely manner? This option will be pretty handy for cases as completing the parent process when the child one dies unexpectedly.

Kind Regards,
Sergey

**Comment by reinra** [comment]
Sorry I somehow skipped reading this issue.

There's method ProcessExecutor.closeTimeout() available for that purpose.

**Comment by szhem** [comment]
@reinra thanks a lot! `closeTimeout` is what I need.
