### ISSUE TITLE
Clarification -- sudo password

### ISSUE THREAD

**Issue by nandhusriram** [zeroturnaround/zt-exec#32]
How do I feed the password to the outputstream?

**Comment by reinra** [comment]
If you mean passing something to the std-in of the forked process you can use the following method:
`processExecutor.redirectInput(new ReaderInputStream(new StringReader("secret")));`

**Comment by nemecec** [comment]
You might also need to add line-break at the end of the password:
`processExecutor.redirectInput(new ReaderInputStream(new StringReader("secret\n")));`

**Comment by nandhusriram** [comment]
Thanks for the clarification , here is what I did new ProcessExecutor(commands)
        .redirectInput(new ReaderInputStream(new StringReader("secret\\r\\n"))).readOutput(true)
        .destroyOnExit().execute().getOutput().getUTF8();

process still hangs waiting for my input.

**Comment by reinra** [comment]
Try to execute the command from the shell using pipe operator to pass the input.
It only works in Java if it works on shell with the pipe operator.
As some commands want to read the password without showing it they might use special console API not the standard input. So in that case you can't achieve it from Java directly. Check the arguments that your command takes. Maybe there's a special flag to use stdin or a password file instead.
