### ISSUE TITLE
Question about memory consumption

### ISSUE THREAD

**Issue by sachinwalia2k8** [zeroturnaround/zt-exec#35]
I've been using https://github.com/brettwooldridge/NuProcess from quiet sometime for triggering Linux processes. It is working well so far. I like zt-exec and wondering how the library perform in terms of memory consumption in the cases where large number of concurrent processes need to be started. Any benchmark would be helpful.

**Comment by reinra** [comment]
NuProcess seems interesting. If your app is performance-critical go for it. Having a benchmark seems like a scope of this NuProcess library.

zt-exec is based on ProcessBuilder by just improving its usability not the performance. By default it uses 1 pumper threads per process as stderr is redirected to stdout. Even if you don't care about the output it just pumps it to NullOutputStream to avoid freezing the forked process. In case of using a timeout it also uses an extra thread for waiting for the process.
