### ISSUE TITLE
JCenter repository is not up to date

### ISSUE THREAD

**Issue by valfirst** [zeroturnaround/zt-exec#36]
JCenter repository: https://jcenter.bintray.com/org/zeroturnaround/zt-exec/ contains artifacts of the version 1.8 and below. But version 1.9 is already available in maven repository: http://repo1.maven.org/maven2/org/zeroturnaround/zt-exec/1.9/.
Could you please upload version 1.9 to JCenter or change sync model for JCenter repository to look up for new version in Maven Central?

**Comment by toomasr** [comment]
I thought it was syncing from Maven central. I went over the settings and can't find why it is not pulling the updated version.

**Comment by valfirst** [comment]
Here is a response from Bintray Support

> Hi Valery,
> 
> Thank you for reaching out.
> 
> In order to address your enquiry let us first elaborate on the sync between JCenter and Maven Central. 
> In general, while the content "belong" to JCenter, artifacts are synced between the two repositories on demand. If artifacts which dosn't exist in JCenter are being requested by a user, they will be resolved to JCenter from remote repositories. 
> In this case, it seems that the package was originally retrieved by JCenter and that its ownership was transferred to you only later, and these files were never requested before the transfer of ownership.
> 
> Now, in order to make sure your package and versions are correctly [synced with Maven Central](https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html) you will need to take the opposite direction. By this we mean that you will need to upload your versions directly to Bintray and use the [Sync to Maven Central option](https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html).
> 
> The reason for this, is that as long as a package is not associated with a user, we will resolve the needed version from external sources. As soon as the package is associated with a user, it is up to this user to maintain the versions.
> 
> Therefore, as mentioned above, we would recommend uploading the files to Bintray and then use the [Sync to Maven Central option](https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html) in order to assure that both locations are aligned with the desired content.
> 
> We hope this explains it.
> 
> Best regards,
> Eran
> JFrog Support

Looks like before artifacts were uploaded to JCenter and then synced to Maven Central. It seems that with such approach backward sync is not supported

**Comment by toomasr** [comment]
Ok, thanks for researching. Not sure who set this up for us but oh well. I've created the version manually and uploaded the artefacts. Can you double check that everything works for you now?

**Comment by valfirst** [comment]
I've checked, the issue is fixed, thank you!
