### ISSUE TITLE
sub-processor never stop !

### ISSUE THREAD

**Issue by NanYoMy** [zeroturnaround/zt-exec#37]
hi, i use zt-exec to run "ffmpeg" commands in my java application. and i set the timeout of the executor like code below:
 new ProcessExecutor().command(cmds.split(" ")).timeout(TIMEOUT, TimeUnit.SECONDS)

when the timeout occurs, it will throw a exception, but it never kill the ffmpeg processor. the ffmpeg still run in background! 

plz help me !!

**Comment by reinra** [comment]
Hi,
You should see in the log that it's actually trying to stop the process. It's calling Process.destroy() method which implementation depends on the OS. On Windows it's forcefully killing and on UNIX it's gracefully killing the forked process - it's up to the process itself whether it decides to stop or not.
Which OS are you using?

**Comment by NanYoMy** [comment]
i solve it thx
