### ISSUE TITLE
StreamPumper should regularly flush OutputStream

### ISSUE THREAD

**Issue by guw** [zeroturnaround/zt-exec#39]
When running on Mac and connecting a process' standard in using `ProcessExecutor.redirectInput(InputStream)` on Java 8 a process may not receive any data until the `OutputStream` is flushed. The reason is that the launched process is a `UNIXProcess` which wraps the `OutputStream` for writing to a process' standard in into a `BufferedOutputStream`.

Proposal: call `out.flush()` immediately after writing any data to `out` in `StreamPumper.run` line 129.

Note, I have not verified this behavior on other platforms but according to [this blog](http://blog.headius.com/2013/06/the-pain-of-broken-subprocess.html), Java seems to be doint it in general for anything using `UNIXProcess`.

**Comment by reinra** [comment]
We can't do it always due to a performance hit but we should make it optional then.

**Comment by guw** [comment]
Agreed. Do you want to always do it for the input?

**Comment by reinra** [comment]
Seems ok to do it for input. Thanks for the pull request. Changes look good.
