### ISSUE TITLE
Need support for MDC logging context

### ISSUE THREAD

**Issue by maruthijr** [zeroturnaround/zt-exec#43]
When we use a logger to redirect process output, it loses any MDC logging context from the provided logger. 
Currently ZT launches a new executor and a thread to execute the process. There is no way to set or pass the logging context to the process execution thread. This is a big pain point when we use ZT to execute processes in cloud where multiple threads, processes and machines are involved. Very hard to debug anything without a logging context.
Easiest way to do this in current zt code is to invoke one of the before listeners from the process thread and not from the calling thread. Alternate way is to provide hooks into the thread executor creation. 
Sample code to show the problem:
`
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import org.zeroturnaround.exec.ProcessExecutor;
import org.zeroturnaround.exec.stream.slf4j.Slf4jStream;

public class Main {
	private static final Logger logger = LoggerFactory.getLogger(Main.class);
	 	 
	public static void main(String[] args) throws Exception {
		MDC.put("jobId", "12232");
		logger.info("Starting ls process");
		ProcessExecutor pe = new ProcessExecutor("ls", "-l");
		pe.redirectOutput(Slf4jStream.of(logger).asInfo());
		pe.execute();
		final Map<String,String> ctxMap = MDC.getCopyOfContextMap();
		new Thread(){
			public void run() {
				MDC.setContextMap(ctxMap);
				logger.info("Log from a child thread");
			};
		}.start();
	}
}
`

Log output from the above code. Notice how the process output does not have the context info (jobId):

`
[main] [jobId=12232] INFO  ztlogmdctest.Main - Starting ls process
[main] [jobId=12232] DEBUG o.z.exec.ProcessExecutor - Executing [ls, -l].
[main] [jobId=12232] DEBUG o.z.exec.ProcessExecutor - Started java.lang.UNIXProcess@5b464ce8
[Thread-0] [] INFO  ztlogmdctest.Main - total 8
[Thread-0] [] INFO  ztlogmdctest.Main - -rw-r--r--  1 maruthir  staff  831 Jan 27 11:42 pom.xml
[Thread-0] [] INFO  ztlogmdctest.Main - drwxr-xr-x  4 maruthir  staff  136 Jan 27 11:36 src
[Thread-0] [] INFO  ztlogmdctest.Main - drwxr-xr-x  4 maruthir  staff  136 Jan 27 11:36 target
[main] [jobId=12232] DEBUG o.zeroturnaround.exec.WaitForProcess - java.lang.UNIXProcess@5b464ce8 stopped with exit code 0
[Thread-1] [jobId=12232] INFO  ztlogmdctest.Main - Log from a child thread
`

**Comment by reinra** [comment]
Hey,
thanks for the feedback!
Do those commits solve the case?

**Comment by maruthijr** [comment]
Wow that was quick! @reinra thanks for the quick fix. I just tried it the logging context now appeared only on the "Waiting for process.." message. A little debugging and I realized that the thread thats actually pushing out process output is the StreamPumper (Sorry did not see this earlier). I tried this fix and it seemed to work ok. Including the patch for your review and inclusion:
`diff --git a/src/main/java/org/zeroturnaround/exec/stream/StreamPumper.java b/src/main/java/org/zeroturnaround/exec/stream/StreamPumper.java
index 41bb905..9183f10 100644
--- a/src/main/java/org/zeroturnaround/exec/stream/StreamPumper.java
+++ b/src/main/java/org/zeroturnaround/exec/stream/StreamPumper.java
@@ -40,9 +40,11 @@ package org.zeroturnaround.exec.stream;
 import java.io.IOException;
 import java.io.InputStream;
 import java.io.OutputStream;
+import java.util.Map;
 
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
+import org.slf4j.MDC;
 
 /**
  * Copies all data from an input stream to an output stream.
@@ -72,6 +74,10 @@ public class StreamPumper implements Runnable {
   /** flush the output stream after each write */
   private final boolean flushImmediately;
 
+  /** Carries the MDC logging context of the parent thread if it exists */
+  private final Map<String,String> mdcContext = MDC.getCopyOfContextMap();
+
+
   /**
    * Create a new stream pumper.
    *
@@ -155,6 +161,9 @@ public class StreamPumper implements Runnable {
    * soon as the input stream is closed or an error occurs.
    */
   public void run() {
+    if (this.mdcContext != null) {
+      MDC.setContextMap(this.mdcContext);
+    }
     log.trace("{} started.", this);
     synchronized (this) {
       // Just in case this object is reused in the future
`
Thanks again

**Comment by reinra** [comment]
Sry for a delay. It shows that I either react quickly or forget about it for weeks.
Improved the code here: https://github.com/zeroturnaround/zt-exec/commit/29e32e0218c8b7719646e8452b4c0008c799506b
