### ISSUE TITLE
Release latest master as new stable release

### ISSUE THREAD

**Issue by karliszigurs** [zeroturnaround/zt-exec#47]
It has been a while since 1.9 and master now contains couple of small, but not insignificant improvements around logging.

Please consider bumping to 1.10 (or maybe 1.9.1) and making it available as stable release.

**Comment by toomasr** [comment]
Makes sense. I'll see if we can get one more fix in for the Android emulator and we'll have a release nevertheless within days.

**Comment by toomasr** [comment]
Scratch that. I mixed up with the zt-zip project. The point the same though. We'll have a release within days.

**Comment by toomasr** [comment]
And done. Latest version 1.10 pushed to Maven Central.
