### ISSUE TITLE
commons-lang 2.6 has vulnerabilities reported by Whitesource

### ISSUE THREAD

**Issue by wattdave** [zeroturnaround/zt-exec#52]
It would be excellent if you could move to using commons-lang3 instead of commons-lang. Today WhiteSource static scanner started reporting two items in commons-lang 2.6 as blocker bugs.

https://issues.apache.org/jira/browse/LANG-1049
https://issues.apache.org/jira/browse/LANG-805

Both are low-impact, but you know how this goes - your customers ask, our customers ask...

**Comment by reinra** [comment]
The scope of this dependency was 'test'. However I bumped it.
