### ISSUE TITLE
Error with handling output line-by-line while process is running code snippet

### ISSUE THREAD

**Issue by tejravic** [zeroturnaround/zt-exec#53]
I'm getting below error while trying out "Handling output line-by-line while process is running".

**Error:**
Error:(27, 33) java: constructor LogOutputStream in class sun.rmi.log.LogOutputStream cannot be applied to given types;
  required: java.io.RandomAccessFile
  found: no arguments
  reason: actual and formal argument lists differ in length

**Test Code**
import org.zeroturnaround.exec.ProcessExecutor;
import sun.rmi.log.LogOutputStream;
import java.io.IOException;

public class TestCmd {
    public static void main(String[] args) throws IOException, InterruptedException {
        new ProcessExecutor().command("java", "-version")
                .redirectOutput(new LogOutputStream() {
                    @Override
                    protected void processLine(String line) {
                        System.out.println("hereeee" + line);
                    }
                })
                .execute();
    }
}

**Comment by reinra** [comment]
You should replace `import sun.rmi.log.LogOutputStream;` with `import org.zeroturnaround.exec.stream.LogOutputStream;`
