### ISSUE TITLE
Is it possible to write stdout to a file?

### ISSUE THREAD

**Issue by RaviH** [zeroturnaround/zt-exec#55]
Hello,

Great work on the library. It looks great. 

Question: is it possible to redirect stdout to a file like in a shell: 'do something > out.txt'

**Comment by reinra** [comment]
Hey,
Since Java 7 you can do it directly without a cost of extra pumping thread:
```
new ProcessBuilder("do", "something").redirectOutput(new File("out.txt")).start();
```
zt-exec doesn't support that directly (yet) but you can pump the output to any stream:

```
try (OutputStream out = Files.newOutputStream(Paths.get("out.txt"))) {
    new ProcessExecutor("do", "something").redirectOutput(out).execute();
}
```

**Comment by alekseysotnikov** [comment]
Does the ProcessExecutor close the outputstream by themselves after calling **execute**?

**Comment by reinra** [comment]
It doesn't. That why I used try {} in the example so it would also close the stream.

**Comment by alekseysotnikov** [comment]
Does it possible to configure ProcessExecutor to close streams automatically and do not use try with resource block?
