### ISSUE TITLE
TimeoutException is never thrown.

### ISSUE THREAD

**Issue by brilliantcontract** [zeroturnaround/zt-exec#56]
Hello, I tried run original test for TimeoutException https://github.com/zeroturnaround/zt-exec/blob/master/src/test/java/org/zeroturnaround/exec/test/ProcessExecutorTimeoutTest.java but it failed.

Also I developed simpler test to make it more readable:

    @Test
    public void testExecuteTimeout() throws Exception {
        try {
            new ProcessExecutor()
                    .command(Lists.newArrayList("sleep","3"))
                    .timeout(1, TimeUnit.SECONDS)
                    .execute();
            Assert.fail("TimeoutException expected.");
        } catch (TimeoutException e) {
            Assert.assertThat(e.getMessage(), CoreMatchers.containsString("1 second"));
        }
    }

    @Test
    public void testStartTimeout() throws Exception {
        try {
            new ProcessExecutor()
                    .command(Lists.newArrayList("sleep","3"))
                    .start()
                    .getFuture()
                    .get(1, TimeUnit.SECONDS);
            Assert.fail("TimeoutException expected.");
        } catch (TimeoutException e) {
            Assert.assertNull(e.getMessage());
        }
    }

This test also failed.

The reason for all fallen tests is the TimeoutException is never thrown.

**Comment by toomasr** [comment]
I'm a bit late to the game but just ran these tests and they pass. Which Java version is this happening with? I added the tests to other TimeoutTests over here https://github.com/zeroturnaround/zt-exec/blob/master/src/test/java/org/zeroturnaround/exec/test/ProcessExecutorTimeoutTest.java and the only changes I made was initiating the ArrayList the old way.

**Comment by brilliantcontract** [comment]
I have just run all tests successfully https://github.com/zeroturnaround/zt-exec/blob/master/src/test/java/org/zeroturnaround/exec/test/ProcessExecutorTimeoutTest.java

In addition I run own simple test for timeout:
<code>    @Test(expected = TimeoutException.class)
    public void testTimeout() throws IOException, InterruptedException, TimeoutException {
        processExecutor.command("sleep", "2")
                .timeout(1, TimeUnit.SECONDS).execute();
    }</code>

**Comment by brilliantcontract** [comment]
Thank you for attention and time.
