### ISSUE TITLE
Problem with running a command with an environment variable.

### ISSUE THREAD

**Issue by brilliantcontract** [zeroturnaround/zt-exec#61]
I couldn't find a test for this case, so I come up with my test case
<pre>    @Ignore("This test constantly fails")
    @Test
    public void testDefineEnvironmentVariable() throws IOException, InterruptedException, TimeoutException {
        String output = processExecutor
                .command("echo", "$foo")
                .environment("foo", "bar")
                .readOutput(true).execute()
                .outputUTF8();

        assertThat(output, containsString("bar"));
    }</pre>

Output: 
![screenshot from 2018-06-23 14-02-24](https://user-images.githubusercontent.com/4412358/41809968-173618be-76ee-11e8-957e-c451514565ed.png)

I expect from method `environment()` to add a variable into environment.
Java `.environment("foo", "bar")` should be console equals `export foo=bar`
So now `echo $foo` should return `bar`, but in the test I got `$foo`.

**Comment by brilliantcontract** [comment]
I use Java 8.171, NetBeans 8.2

**Comment by nemecec** [comment]
Expanding environment variables like you expect is a feature of the command line shell. Something like this should work:

```
    @Ignore("This test constantly fails")
    @Test
    public void testDefineEnvironmentVariable() throws IOException, InterruptedException, TimeoutException {
        String output = processExecutor
                .command("/bin/sh", "-c", "echo $foo")
                .environment("foo", "bar")
                .readOutput(true).execute()
                .outputUTF8();

        assertThat(output, containsString("bar"));
    }

```

**Comment by brilliantcontract** [comment]
`.command("/bin/sh", "-c", "echo $foo")`
It works just great!
Thank you.
