### ISSUE TITLE
Converted to UTF-8 encoding format, still scrambled

### ISSUE THREAD

**Issue by sfx478076717** [zeroturnaround/zt-exec#67]
Converted to UTF-8 encoding format, still scrambled
`String cmdCode = "ipconfig";`
       ` String output = new ProcessExecutor().command(cmdCode)
                .readOutput(true).execute()
                .outputUTF8();`
`        System.out.println(getEncode(output));`
    `   System.out.println(output);`

**Comment by toomasr** [comment]
Is there an easy way how to reproduce this? A simple test case or similar would help to debug this.

**Comment by toomasr** [comment]
Do you have a test case that would be easy to reproduce with? Running this example without the provided getEncode() method doesn't produce anything scrambled on my machine.

I presume you are using non-english names in the device names of ipconfig? Also you might have an encoding for ipconfig output that is not utf8?
