### ISSUE TITLE
Remove dependency on commons IO?

### ISSUE THREAD

**Issue by ketan** [zeroturnaround/zt-exec#69]
There appear to be 2 (rather simple) classes from commons-io that are used by zt-exec.

This seems to pull down an entire library (and an older version of it). Would there be interest in a PR that includes a simple implementation of `TeeOutputStream` and `NullOutputStream` as part of zt-exec and remove the dependency on commons-io altogether?

**Comment by toomasr** [comment]
Thank you, merged.
