### ISSUE TITLE
Version 1.11 contains JRebel file with Toomas' user dir :D

### ISSUE THREAD

**Issue by bsideup** [zeroturnaround/zt-exec#72]
If you look inside zt-exec 1.11 jar, there is "rebel.xml" file (I guess it was added by mistake) with @toomasr's user dir (I assume he was releasing the library ;)):
<img width="943" alt="Screenshot 2019-07-19 at 3 06 00 PM" src="https://user-images.githubusercontent.com/1050762/61537204-daf5ab80-aa36-11e9-951d-2d46ab00e31e.png">

We discovered it in @testcontainers when our shading tests started failing because of an unexpected "rebel.xml" file in the resulting JAR 😅

**Comment by toomasr** [comment]
Quite unprofessional of me 😇. Let me know if a new version is needed bronto. I'm on limited internet.

**Comment by bsideup** [comment]
@toomasr no rush! :) And don't worry... it happens to the best of us :D

**Comment by ksilz** [comment]
@toomasr I believe this issue is still there in the current release. Will it ever be fixed?

**Comment by toomasr** [comment]
I was kind of hoping that I can release this with bunch of other improvements but has none has happened for a year I believe 1.12 is in order.

I've done the release to maven central (might be a delay to show up there) BUT as I don't have write access to the repo anymore for I don't know what reason then I was not able to push my changes. I've queried some people about it and let's see if I'll regain the the access or not but nevertheless maven central should have 1.12 without the embedded rebel.xml.

**Comment by toomasr** [comment]
And now also pushed. Enjoy!
