### ISSUE TITLE
Running Process with VM Memory Settings causes creation of VM failing

### ISSUE THREAD

**Issue by dangllucas** [zeroturnaround/zt-exec#73]
When starting a Process with:
`new ProcessExecutor("java", "-Xms64m", "-Xmx128m", "-jar", "<pathToJar>").start();`

The Creation of the Java Virtual Machine fails with following Message:

`Invalid initial heap size: -Xms64m -Xmx128m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

Starting the Process without the Memory Settings makes the Process execute normally.

Tested on Windos and Unix, same error occurs.

Is there any solution to this?

**Comment by toomasr** [comment]
Not sure this is connected to zt-exec. There are solutions at https://stackoverflow.com/questions/16416832/invalid-initial-heap-size-could-not-create-the-java-virtual-machine Maybe some of them will help you.
