### ISSUE TITLE
ProcessExecutor getPid?

### ISSUE THREAD

**Issue by dinuta** [zeroturnaround/zt-exec#80]
Hi guys,

Is there a possibility to get the Pid somehow from ProcessExecutor? Or use some other combination?

Sample here:  https://github.com/dinuta/estuary-testrunner-java/blob/master/src/main/java/com/github/dinuta/estuary/testrunner/utils/CommandRunner.java **line 205**

Cheers,
Catalin

**Comment by nemecec** [comment]
`ProcessExecutor.start()` method returns instance of `StartedProcess` - you can invoke `getProcess()` on this to get instance of `java.lang.Process`. From here, you can just follow the standard Java way.

For some inspiration about the "Java way", see https://stackoverflow.com/questions/4750470/how-to-get-pid-of-process-ive-just-started-within-java-program.

**Comment by dinuta** [comment]
Hi @nemecec,

Yes I know, but I need TimeoutException for system commands with a user configured timeout. So I use processExecutor.execute().

If I use your method how can the command timeout? I need this to not keep the service locked if something goes wrong.
You can look starting with line 196.

BR
Catalin

**Comment by nemecec** [comment]
In case you need to time out, you can use `StartedProcess.getFuture()` and then use `Future.get()` with timeout.

**Comment by dinuta** [comment]
Thank you.
