### ISSUE TITLE
Question: How I can pickup stderr from ProcessResult

### ISSUE THREAD

**Issue by dinuta** [zeroturnaround/zt-exec#81]
```
  ProcessResult processResult = processState.getProcessResult().get(timeout, TimeUnit.SECONDS);
  int code = processResult.getExitValue();
  String err = (code == 0) ? "" : processResult.getOutput().getString();
```

I want to pick up from a Process class stderr using your lib.

This piece of code is not correct since there are commands where exit status is 0 but it logs the result in stderr. E.g. ```java -version```

How can I pickup stderr reliably?

Thanks guys,
Catalin

**Comment by nemecec** [comment]
There is a sample for redirecting stderr to a separate stream on https://github.com/zeroturnaround/zt-exec/:

```
String output = new ProcessExecutor().command("java", "-version")
        .redirectError(Slf4jStream.of(getClass()).asInfo())
        .readOutput(true).execute()
        .outputUTF8();

```
Feel free to replace `Slf4jStream.of(getClass()).asInfo()` with some other `OutputStream` instance.

**Comment by dinuta** [comment]
Thanks @nemecec . Will give it a try!

**Comment by dinuta** [comment]
Hi @nemecec ,

Do you think is fine? Tested and looked fine. Please have a look:
https://github.com/dinuta/estuary-agent-java/pull/23/files

**Comment by nemecec** [comment]
Are you sure about your test?
As much as I know about piped streams in Java, you are not using them correctly. http://tutorials.jenkov.com/java-io/pipedinputstream.html

I added some comments on the pull request.

**Comment by dinuta** [comment]
Thanks man for your time.

Did some changes here: 
Yes the streams were not used properly, but my integration tests passed ... The service seemed to put stdout and stderr properly in the HTTP response.

https://github.com/dinuta/estuary-agent-java/pull/24/files

I will close this with many thanks.
Catalin
