### ISSUE TITLE
Java 11 Support

### ISSUE THREAD

**Issue by SudharakaP** [zeroturnaround/zt-exec#82]
We have a project that uses Java 11 and I was wondering if this library and [zt-process-killer](https://github.com/zeroturnaround/zt-process-killer) supports Java 11? 🤔

**Comment by toomasr** [comment]
Just take it for a spin. The code was written in the era of Java 1.5 and Java 1.6 (the current compile target) and was battle tested while being at some core functionality of a commercial offering. It does not use any of the jdk9 process api improvements though.

**Comment by SudharakaP** [comment]
@toomasr : Thanks much for the information. Yes; let me try it out. 😄
