### ISSUE TITLE
Support for Linux pipe command

### ISSUE THREAD

**Issue by JVictorio** [zeroturnaround/zt-exec#83]
Hi there,  I'm wondering if this library supports linux pipe command?  I'm using a command like this: "jcmd -l | grep '*.jar' | cut -d ' ' -f 1".  I tried separating each command as per your documentation but it doesn't work.  Even if I shorted the command to "jcmd -l | grep '*.jar' ", it does not work.

Can you please let me.

Thanks
Jun Victorio9

**Comment by nemecec** [comment]
Piping input and output streams is a feature of the command line shell. zt-exec only executes commands, it does not provide any features that you would find in a shell.
You could either implement the piping functionality in your Java code or you can create a shell script with the piping command and call the script from your Java code (with zt-exec), for example `new ProcessExecutor().command("/bin/bash", "/path/to/my/script.sh").execute();` In case you decide to create a script, make sure your execution environment is appropriately set up (PATH, etc).

**Comment by gsylvie** [comment]
Try this:

`command("sh", "-c", "jcmd -l | grep '.jar' | cut -d ' ' -f 1 ");
`
