### ISSUE TITLE
How to select cmd or PowerShell when running on windows?

### ISSUE THREAD

**Issue by venustulips** [zeroturnaround/zt-exec#96]
Hi,

I have a command to run which is specifically to run with cmd.exe

Is there any parameter setting where I can specify the underlying execution env such as cmd or PowerShell?

PowerShell is being selected automatically as default on my machine which I do not want.

**Comment by nemecec** [comment]
`zt-exec` does not use any specific shell for execution, it invokes the commands directly. You could of course execute `cmd.exe` with appropriate parameters.
