### ISSUE TITLE
Changing directory support

### ISSUE THREAD

**Issue by dinuta** [zeroturnaround/zt-exec#97]
HI team,

I integrated your lib in a spring-boot service to execute remote commands.
I want to develop a CLI, similar to SSH which can execute commands remotely on this service. Since the service is stateless, I wonder how I can make the client aware of the execution path (folder path) after the execution of the command.

System.getProperty(user.dir) does not help me in this matter.

Is there a way to integrate in zt-exec a feature where we can catch the actual working dir after the command was executed? 

Examples:
Considering that user.dir=C:\\Users\\dinuta
> ls 
work
.
..

> INPUT: pwd => OUTPUT: C:\\Users\\dinuta
> INPUT: cd work && ./filebeat.exe => OUTPUT: C:\\Users\\dinuta\\work

Thanks,
Catalin

**Comment by nemecec** [comment]
`cd` command is implemented by the shell (bash, fish, zsh, etc). `zt-exec` does not use any shell for execution, so this command does not work -- you would need to implement support for such a command yourself, in your Java code.

From [cd command](https://en.wikipedia.org/wiki/Cd_(command)) Wikipedia page:
> `cd` is frequently included built directly into a command-line interpreter. This is the case in most of the Unix shells (Bourne shell, tcsh, bash, etc.), cmd.exe on Microsoft Windows NT/2000+ and Windows PowerShell on Windows 7+ and COMMAND.COM on DOS/ Microsoft Windows 3.x-9x/ME.

**Comment by dinuta** [comment]
Thanks, closing this
